name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      env:
          FUNCTIONAL_TEST_TOKEN: 54270719-40B5-4DF9-AC02-2A8597DBC614
      run: |
        xcodebuild \
        -project EnvironmentVariables.xcodeproj \
        -scheme "EnvironmentVariables (iOS)" \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 12' \
        test
